# 配置springtask 定时任务相关的配置

spring:
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: hanhan
    execution:
      shutdown:
        #        线程关闭时是否等所有任务结束
        await-termination: false
        #        线程最大的等待时间，防止线程陷入循环关不掉
        await-termination-period: 10s